version: "3.7"
services:
  server:
    build:
      context: .
    image: ovloop-api
    volumes:
      - ./back/src:/app/src
    container_name: ovloop-api-dev
    ports:
      - 8080:8080
      - 2345:2345
      - 9229:9229
    depends_on:
      - localstack
      - mongo
      - front
    environment:
      NODE_ENV: local
      REGION_SNS: us-east-2
      AWS_ACCESS_KEY_ID: anykey
      AWS_SECRET_ACCESS_KEY: anysecret
    tty: true
    entrypoint: ["npm", "run", "local"]
  front:
    image: ovloop-front
    container_name: ovloop-front_container
    ports:
      - "7777:7777"
    depends_on:
      - mongo
    environment: 
      NODE_ENV: local
      API_HOST: server
      API_PORT: 8080
  localstack:
    image: localstack/localstack
    container_name: ovloop-api_localstack
    environment:
      # LOCALSTACK_HOSTNAME: localstack
      SERVICES: "sns,sqs"
      DEFAULT_REGION: us-east-2
    ports:
      - 8070:8080
      - 4575:4575
      - 4576:4576
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
networks:
  default:
    name: ovloop-app


    #     # front/docker-compose.yml
# version: '2'
# services:
#   front:
#     ...
#     networks:
#       - some-net
# networks:
#   some-net:
#     driver: bridge


# # api/docker-compose.yml
# version: '2'
# services:
#   api:
#     ...
#     networks:
#       - front_some-net
# networks:
#   front_some-net:
#     external: true